### ISSUE TITLE
Does this plugin compatible with WebStorm 2022.3?

### ISSUE THREAD

**Issue by NikitaSheff** [mbolotov/intellij-cypress#112] opened 2022-12-01 13:09 UTC
![image](https://user-images.githubusercontent.com/99482593/205060927-600e3dad-42e1-447a-ba19-c8033870f12d.png)
I can't create cypress run cofiguration
**Versions**:
- Cypress Cupport
- IDE: WS
- OS: Win11

**Comment by mbolotov** [comment] 2022-12-02 13:16
Please specify version of the plugin

**Comment by NikitaSheff** [comment] 2022-12-02 13:34
The latest - 1.4.3

**Comment by mbolotov** [comment] 2022-12-02 14:23
can you provide a sample project to reproduce the problem?

**Comment by PhilippeRT** [comment] 2023-01-09 22:38
Hello,

I've got the same problem as Nikita.
I just tried with the kichensink example

Thanks

**Comment by mbolotov** [comment] 2023-01-10 09:11
Hi @PhilippeRT!
do you mean this project: https://github.com/cypress-io/cypress-example-kitchensink.git
?
I'm unable to reproduce the problem with it.
Could you try [this plugin bundle](https://github.com/mbolotov/intellij-cypress/files/10347289/Cypress.Support-1.5.1-DEBUG.zip) with additional logging and post the log file here?

**Comment by PhilippeRT** [comment] 2023-01-11 06:43
Hello @mbolotov 

It seems that the new version it better integrated :-D.
I did not have to manually create the configuration for the entire file, the runner is automatically detected by WebStorm (even if it does not appear in the menu), and i could run a single test, not the entire file.

Good job :+1:

When this version will be released ?

THANKS a lot

**Comment by mbolotov** [comment] 2023-01-13 19:50
@PhilippeRT 
I will release the version soon.
As for the  ` Unable to add a .only keyword` error, could you provide the logs if you are able to reproduce it stably?

**Comment by mbolotov** [comment] 2023-01-16 18:45
should be fixed in 1.5.1 version

**Closed by mbolotov** 2023-01-16 18:45 UTC
Labels: base version
