### ISSUE TITLE
Cypress runner doesn't detect specs in nested dirs

### ISSUE THREAD

**Issue by martaver** [mbolotov/intellij-cypress#55] opened 2021-08-02 09:52 UTC
I have a project with two source roots, where cypress is installed under `./client/`.

In this case I've set up my run configuration so that:
'Cypress project base' is `<repo_path>/client`.
'Test directory' is `<repo_path>/client/cypress/integration`, and I have selected 'All in directory'.

My specs are in nested directories underneath /integration, however Cypress runner doesn't find them.
Cypress runner only finds specs that are direct descendants of the 'Test directory' path.

I'm trying to run cypress in Interactive mode.

**Comment by mbolotov** [comment] 2021-08-03 14:33
I was unable to reproduce the problem as you described.
But I changed the path that is passed to cypress runner from relative to absolute.
@martaver, could you please check if this worked okay for you? Please take bundle with the fix from #54

**Comment by mbolotov** [comment] 2021-09-30 07:19
closing as no feedback received.
feel free to comment/create a new issue if problem persists

**Closed by mbolotov** 2021-09-30 07:19 UTC
