### ISSUE TITLE
plugin crash sometimes

### ISSUE THREAD

**Issue by Areen3** [mbolotov/intellij-cypress#39] opened 2021-02-20 15:37 UTC
Hi, 
I run plugin under NX but sometime I have:

![image](https://user-images.githubusercontent.com/34617740/108600883-d4a97d00-7399-11eb-87ca-55f5cd2d3b15.png)

and 
![image](https://user-images.githubusercontent.com/34617740/108600898-ed199780-7399-11eb-8dca-72a7b1a66c4c.png)

**Comment by mbolotov** [comment] 2021-02-20 16:01
Hi 
Do you notice any function loss when see these exceptions?
Do you know how to reproduce them?

**Comment by Areen3** [comment] 2021-02-20 19:18
not at the moment
because I am writing cypress related code and using a plugin
I watch it
I'll let you know, give me a few days

**Comment by bordelman** [comment] 2021-05-06 10:18
Hi
I do have this issue too. For me there is problem with custom commands. They are not autocomplating. That appeared after updating pycharm to 2021.1

**Comment by Areen3** [comment] 2021-05-06 18:28
hi 
problem was in nx that generate not exactly working code
when I comment processTypescipr and webpack it start working in plugins
now it looks like: 

![image](https://user-images.githubusercontent.com/34617740/117347527-817b9c80-aea9-11eb-844f-5132e5794cb6.png)
I wrote about it on github nx, look there

**Comment by mbolotov** [comment] 2021-05-09 16:07
> Hi
> I do have this issue too. For me there is problem with custom commands. They are not autocomplating. That appeared after updating pycharm to 2021.1

Hi @bordelman!
Please create a separate issue if you have a problem with autocomplete.

**Comment by mbolotov** [comment] 2021-07-16 12:13
hi @Areen3!

Do you think this issue may be closed as the problem is/was on the nx side?

**Comment by Areen3** [comment] 2021-07-16 12:48
The problem was on my side and the correct configuration of the paths in the cypress site,
can be closed
thank you for the time ...

**Closed** 2021-07-16 13:32 UTC
