### ISSUE TITLE
Debugger not stopping at breakpoints

### ISSUE THREAD

**Issue by bensullivan-ag** [mbolotov/intellij-cypress#102] opened 2022-08-15 06:53 UTC
Hi

I am trying to debug my cypress code with the debugger in the pro version of the plugin.  I've tried latest versions of IDEA Ultimate and WebStorm and neither seems to work.  See attached screencast..

Are there any magic sprinkles you can offer?

Thanks

Ben

**Comment by mbolotov** [comment] 2022-08-15 15:09
Hi @bensullivan-ag 
first of all, to be on the safe side, are you sure that the execution goes through the line with your breakpoint?
could it be that the test fails, for example, on a `beforeEach` hook?
Also, can you check if the `Scripts` tab shows the source maps for your test?
![image](https://user-images.githubusercontent.com/19785715/184661217-4209fd77-8816-4d74-87f5-84853340f1de.png)

**Comment by bensullivan-ag** [comment] 2022-08-15 23:24
Hi @mbolotov 

Even if I put a breakpoint on a line that initialises the script the debugger does not stop.  I have folders in the Scripts tab but they appear to be empty.

**Comment by mbolotov** [comment] 2022-08-16 09:08
Could you try any Cypress public project to see if the issue is related to your project setup or your environment?
For example, you can try this one: https://github.com/cypress-io/cypress-example-kitchensink

**Comment by bensullivan-ag** [comment] 2022-08-16 09:16
sure thing - good idea; attached is also my IDE version:

<img width="450" alt="Screen Shot 2022-08-16 at 19 15 31" src="https://user-images.githubusercontent.com/102003293/184844065-3675ef78-2fbf-436f-bfd5-0bb3daa26cbc.png">

**Comment by bensullivan-ag** [comment] 2022-08-16 10:15
ok - so I can't run kitchen sink with plugin either (works from cli).  Here's a screencast:

[](https://www.dropbox.com/s/x78673fsk0icuvd/Kapture%202022-08-16%20at%2019.47.09.gif?dl=0
)

**Comment by bensullivan-ag** [comment] 2022-08-16 10:24
OK - so if I create a cypress run config and set a breakpoint, I can step through the kitchen sink.

**Comment by mbolotov** [comment] 2022-08-16 11:55
That's probably related to issues with source map configuration. Do you use `Webpack` or any other build tool in your project?

**Comment by mbolotov** [comment] 2022-08-16 11:56
is that possible to share your project with me?

**Comment by bensullivan-ag** [comment] 2022-08-16 13:15
> is that possible to share your project with me?

Afraid not.

It's a gargantuan monorepo.

Any suggestions I could check for on this end?

**Comment by mbolotov** [comment] 2022-08-16 18:12
not many without details of your project setup.

you can try devtools to see if [their debugger](https://vimeo.com/242961930#t=264s) works okay or not with your project. 
if it does not stop on breakpoints either, that means there is nothing I can do on the plugin side.

**Comment by bensullivan-ag** [comment] 2022-08-16 23:45
OK - that's a shame..

**Comment by mbolotov** [comment] 2022-08-23 08:12
@bensullivan-ag 
I think this issue may be closed as there doesn't seem to be anything wrong with the plugin itself. what do you think?

**Comment by mbolotov** [comment] 2022-09-02 11:13
closing this issue as not reproducible and seems not related to the plugin at all.

**Closed by mbolotov** 2022-09-02 11:13 UTC
