### ISSUE TITLE
How to set up for individual tests?

### ISSUE THREAD

**Issue by jeffersondarcy** [mbolotov/intellij-cypress#35] opened 2021-01-26 16:52 UTC
I have managed to set-up the plugin to run all the tests (option "all in directory") but having troubles setting it up to run individual test files or single tests (Error: Cypress spec must be defined). 
When I am trying to run single file I am getting an error because of incomplete configuration and the file name is not set automatically.  
For individual tests no cypress option appears - only mocha or jest. (it might be possible that the file naming collides, but cypress tests are in a different directory)

**Comment by mbolotov** [comment] 2021-01-27 21:02
hi @jeffersondarcy!
The easiest way to setup a run configuration for an individual cypress spec (or a test inside it) is to use run gutters:
![image](https://user-images.githubusercontent.com/19785715/106053377-d44ff600-60fb-11eb-8611-35b3c6cdacb3.png)
Right click on a gutter and create a corresponding run configuration.

Could you please attach a screenshot where you see the problem?

**Comment by jeffersondarcy** [comment] 2021-01-28 16:39
I don't have any cypress options, only jest and mokka
<img width="529" alt="Screenshot 2021-01-28 at 17 34 50" src="https://user-images.githubusercontent.com/4200365/106169424-a61bf600-618f-11eb-8b20-cbb841294f97.png">

**Comment by mbolotov** [comment] 2021-01-28 16:48
Okay, it means the plugin does not treat your test as a cypress one.
Could you share you project? 
If this is not possible, could you at least describe your tests structure? Do you have your tests outside of a directory tree where the `cypress.json` is placed?

**Comment by jeffersondarcy** [comment] 2021-01-29 09:56
tests are located in directory `e2e/tests`, cypress.json is located in directory `e2e`.  
tests are placed in subfolders by suite for example `e2e/tests/cart` and named like blabla.test.ts

**Comment by mbolotov** [comment] 2021-01-29 10:45
Unfortunately, I unable to reproduce the problem
![image](https://user-images.githubusercontent.com/19785715/106265478-2302aa80-6238-11eb-96c5-aeb6d34ca561.png)

Could you share your project somehow? Or create another reproducible sample?

**Comment by jeffersondarcy** [comment] 2021-01-29 12:49
unfortunately I can't share the project. I will maybe try it with a new project to see if it works

**Comment by Mukheem** [comment] 2021-03-26 06:57
Hello @mbolotov ,

I also see the same issue as faced by @jeffersondarcy .

I used Cypress support free version and Pro version(Trial) one after the another with Intellij Ultimate edition and observed that test cases are recognized by free version and can execute them by just _right clicking on spec file  --> select cypress_ as its runner(with appropriate configuration of course)

However, Pro version fails to identify test cases. I managed to configure them manually by changing the spec file name in the same run configuration which was created by free version.

Test case folder structure is **`projectFolder/myProjectName/cypress/integration/myFolderName/testSpecfile.js`**

Please be noted that my cypress.json file is under **projectFolder/myProjectName/cypress.json**

It would be really appreciable if this issue is solved.

**Comment by mbolotov** [comment] 2021-03-26 08:31
Hi @Mukheem!
Could you share your project to reproduce the problem?

**Comment by Mukheem** [comment] 2021-03-26 08:34
@mbolotov ,

I cannot share the project adhering to my Organization's policies.

Let me know if it is okay if I reach out to you on your personal mail id to figure out the issue.

**Comment by mbolotov** [comment] 2021-03-26 08:39
yes, feel free to mail me or join to the plugin's slack channel: https://join.slack.com/t/intellij-cypress/shared_invite/zt-g5lcy9xc-F3qy_g8O~qbZvKjD2m0EjQ

**Comment by mbolotov** [comment] 2021-04-18 17:26
Hi @jeffersondarcy!
Are you still experiencing the problem?

**Comment by mbolotov** [comment] 2021-05-13 14:42
@jeffersondarcy I'm closing as there was no answer from you
fell free to create a new issue with details if you have any problems

**Closed by mbolotov** 2021-05-13 14:42 UTC
