### ISSUE TITLE
Where log is supposed to be shown

### ISSUE THREAD

**Issue by jradom** [mbolotov/intellij-cypress#23] opened 2020-10-12 06:09 UTC
Hello Mikhail,

I'm pretty new to Cypress and try executing the below code

describe('I am on UPS page', () => {
    it('should see ups page', () => {
        cy.visit('/');
        cy.visit('https://www.ups.com/us/en/Home.page');
        let a:number = 5;
        console.log('AAAAAAAAAAAAA===================================> ');
    });
})

I put a breakpoint here, it didn't even stop on. a first cy.visist
![image](https://user-images.githubusercontent.com/20550461/95710756-2dac1c00-0c16-11eb-944d-4d4201a3adc2.png)

I also can't find result from         console.log('AAAAAAAAAAAAA===================================> ');
Oh, I use Typescript
I thought that results will show in the IntelliJ Debug window but it's not there
![image](https://user-images.githubusercontent.com/20550461/95711004-b3c86280-0c16-11eb-98d8-7c024a729965.png)

![image](https://user-images.githubusercontent.com/20550461/95711031-cb075000-0c16-11eb-8773-7268c6fad5af.png)

![image](https://user-images.githubusercontent.com/20550461/95711208-26d1d900-0c17-11eb-865c-65ba086de6a4.png)

Idid imstall/unstal again and got this
![image](https://user-images.githubusercontent.com/20550461/95714226-c180e680-0c1c-11eb-8532-3a0b0d0fddde.png)

Please help

Thanks

Jeff

**Comment by mbolotov** [comment] 2020-10-12 11:11
Hi @jradom!

I see you have both free and paid plugins enabled at the same time. That's the problem.  Please disable the free version here:
![image](https://user-images.githubusercontent.com/19785715/95740008-70143e00-0c94-11eb-96e3-1d5eb7ba6a6f.png)

and restart IDE.

As for the logging issue: this is the Cypress behavior; see here for instance: https://github.com/cypress-io/cypress/issues/186
You can easily get log printed to sdout using such a command:
```     
on('task', {
        log (message) {
          console.log(message)
          return null
        }
      })

**Comment by jradom** [comment] 2020-10-12 15:25
I did what you've suggested but 
        cy.visit('/');
is still not stopped on during debugging.

Please, advise

Thanks

Jeff

**Comment by mbolotov** [comment] 2020-10-12 15:45
Could you please try debug with some delay before the breakpoint.
For example you can add such a before hook:
```    
    beforeEach(() => {
        cy.wait(2000)
    })
```
And check if the first breakpoint stops the execution in this case.

**Comment by jradom** [comment] 2020-10-12 16:25
So, my code looks like now
![image](https://user-images.githubusercontent.com/20550461/95769392-a938b800-0c6c-11eb-9e8c-bb8b491c4eda.png)

But Cypress doesn't move to URL opening
![image](https://user-images.githubusercontent.com/20550461/95769452-c1103c00-0c6c-11eb-8283-4299b0478932.png)
  Any suggestions?

FYI, I was born and raised in Leningrad

Thanks

Jeff

**Comment by mbolotov** [comment] 2020-10-12 18:31
> FYI, I was born and raised in Leningrad

Oh, that's a really cool coincidence! :)

Could you attach a copy of your project?
I'm unable to reproduce the problem on my sample one.

**Comment by jradom** [comment] 2020-10-13 04:42
here you are ...


[Archive.zip](https://github.com/mbolotov/intellij-cypress/files/5368970/Archive.zip)

**Comment by mbolotov** [comment] 2020-10-13 06:53
Unfortunately, I cannot reproduce the problem on your project either. 
![image](https://user-images.githubusercontent.com/19785715/95825396-76102a80-0d39-11eb-99ed-65b247141252.png)

I will ask you if any idea how to troubleshot this comes to my mind...

**Comment by jradom** [comment] 2020-10-13 14:13
But without Beforeeach 
![image](https://user-images.githubusercontent.com/20550461/95872340-8ddcb400-0d23-11eb-8283-9eafbf288db9.png)

I see this
![image](https://user-images.githubusercontent.com/20550461/95872389-98974900-0d23-11eb-8b54-63666c5b280f.png)

**Comment by mbolotov** [comment] 2020-10-13 14:38
Yes, this is an expected behavior.
[Cypress commands are asynchronous](https://docs.cypress.io/guides/core-concepts/introduction-to-cypress.html#Commands-Are-Asynchronous), so the runner just saves them in a queue when the code is 'executed'. And they will really executed later. 
So when your breakpoint is hit, the runner is just collecting the commands. 
If you want to stop when the command is actually get executed, you can set a breakpoint in a `then` block, for example:
![image](https://user-images.githubusercontent.com/19785715/95875642-e68b6b80-0d7a-11eb-9db6-6f6ab928fd99.png)

**Comment by jradom** [comment] 2020-10-13 14:59
Well, but in this case what is the point of using your plugin with breakpoint which moves but the execution of a Cypress code doesn't move together?  I'm lost on the purpose of your tool breakpoints.  Please, clarify

Thanks

Jeff

**Comment by jradom** [comment] 2020-10-13 15:03
The whole point with having a breakpoint is to see where are you in UI but I don't see how that can be achieved

**Comment by mbolotov** [comment] 2020-10-13 15:21
The commands are executed in the same order as they are written. 
So you can insert a 
```
cy.wrap(null).then(() => {
   // set any statement here and put a breakpoint on it
} ) 
```
block where you want to get the execution paused.

Beside that, a real Cypress test often has many synchronous blocks like `then` and `should` where you can put a breakpoint directly.

**Comment by jradom** [comment] 2020-10-13 15:39
Well, it's still not clear to me how I can use your breakpoint and making some changes to the above code and see UI movements in a Cypress browser.  I'm coming from many hears of using Selenium but I had the impression that Cypress wraps asynchronous events and makes code synchronous the way I had used it above.  Is it not a case?

**Comment by jradom** [comment] 2020-10-13 15:50
BTW, in your screenshot above, it passed visit command but still UPS page is not shown in the runner.  Is it a way to do it at all?

**Comment by mbolotov** [comment] 2020-10-13 16:34
I just cut off the app window in the screenshot, it was actually here (but note that in my example it's not UPS page but the Cypress sample one)
As for the usage of breakpoints and sync/async stuff: there is no way to debug async commands in a synchronous way. 
You cannot say the debugger to 'Step Over' from one command to the other and **expect** it get executed in the same time (and so to see the UI movements).
The debugger does not know when the command will actually be executed. Cypress hides this machinery somewhere in the deep and does not provide any API to hook up by the debugger. 
The only way to catch the moment when commands are really executed is to go into a synchronous block and put a breakpoint here (or use 'Run to Line' command for example). 
I'm not sure if I answered all of your questions. Please don't hesitate to ask me more.

**Comment by jradom** [comment] 2020-10-13 17:02
Have you ever used Selenium or any other similar tool?

**Comment by mbolotov** [comment] 2020-10-13 17:21
yes, a little bit

**Comment by mbolotov** [comment] 2020-10-13 17:24
BTW, could you be more easy to talk in a slack channel? 
I have one dedicated for the plugin: https://join.slack.com/t/intellij-cypress/shared_invite/zt-g5lcy9xc-F3qy_g8O~qbZvKjD2m0EjQ

**Comment by jradom** [comment] 2020-10-13 17:26
Let's say I have a page like this
![image](https://user-images.githubusercontent.com/20550461/95894631-3861d080-0d3e-11eb-8ea5-a61342e5ba49.png)
So, using Selenium for example with a breakpoint I can easily see all the steps of filling fields, etc.  So, I understood that I can't do it using Cypress even with the help of your tool brreakpoints

**Comment by jradom** [comment] 2020-10-13 17:28
I've tried this but got a runtime error
    it('should see ups page', () => {
        cy.visit('/').then( () => {
            cy.task('log', 'YYYYYYYYYYYYYYYYYYYYY=============> ' + 'URL visit');
        })
        cy.task('log', 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=============> ' + 'Step1');
        cy.get('#canada').click();
        let a:number = 5;
        cy.task('log', 'BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB=============> ' + 'Step2');
    });

**Comment by mbolotov** [comment] 2020-10-13 17:32
> So, using Selenium for example with a breakpoint I can easily see all the steps of filling fields, etc. So, I understood that I can't do it using Cypress even with the help of your tool brreakpoints

You can do this if you set an additional sync block after each of the command (and set a breakpoint into each or use 'Run to cursor' debugger command)

**Comment by mbolotov** [comment] 2020-10-13 17:33
> I've tried this but got a runtime error
what's error?

**Comment by mbolotov** [comment] 2020-10-20 13:56
Hi Jeff!
I've added a note on debugging Cypress commands in the readme page. 
Do you have any other problems now? I will close the issue otherwise.

**Comment by jradom** [comment] 2020-10-20 14:39
Hi Mikhail,

I still want to understand a purpose of debugging with breakpoints if I can’t see command moving forward in a Cypress runner window. Please, clarify 

Thanks

Jeff

**Comment by mbolotov** [comment] 2020-10-20 15:34
Debugger can helpfull for debugging any **synchronous** code. A real large Cypress test project usually contains a lot of complex synchronous code where breakpoints can be used.
Does this answer your question?

**Comment by jradom** [comment] 2020-10-20 18:20
Can you provide a simple example please?

**Comment by mbolotov** [comment] 2020-10-20 19:25
I mean the pure Cypress commands cannot be debugged (as they are asynchronous), but you may easily make a synchronous block whenever you want.  
Something like this (a quote from issue #24):
```
it('go to schedule and click a data', () => {
  cy.loginAs(admin);
  cy.visit('/schedule#/schedule/new').then(() => {
       console.log("you can set a breakpoint at this line and get the execution paused after the 'visit' command get actually executed (so when the test open your page)" 
  })
  cy.get("#sampleid").click().then(() => {
       console.log("at this time, your test has finished clicking")
})
```

You can put a breakpoint at the lines with console output and got them working as expected.

You can also check for Cypress official docs about debugging: https://docs.cypress.io/guides/guides/debugging.html#Using-debugger
They are talking about 'debugger' statement, but you can apply it to the breakpoints as well.

**Closed** 2020-11-09 18:07 UTC

**Comment by jradom** [comment] 2020-11-10 06:40
Hi Mikhail,

I've for some reason in several projects started to see this when using your plugin but command npx works fine
![image](https://user-images.githubusercontent.com/20550461/98636883-82f25080-22dc-11eb-8876-fa901129f100.png)
It'll be great if can suggest something

Thanks

Jeff

**Comment by mbolotov** [comment] 2020-11-10 07:01
Hi Jeff, 

Could you provide more information on that? Based on this screenshot I cannot say what's going on. 
Do you start seeing this when upgraded to 1.6.2, right?
Could you at least unfold the stacktrace element on the error message which you provided.

**Comment by jradom** [comment] 2020-11-10 07:32
here you are ...
**Message:** Error writing to: <span
class="ansi-blue-fg">`/cypress.json`</span>

<span class="ansi-yellow-fg">`Error: EROFS: read-only file system, open
'/cypress.json'`</span>

**Stack trace:**
```
Error: Error writing to: [34m`/cypress.json` [39m

[33m`Error: EROFS: read-only file system, open '/cypress.json'` [39m
    at Object.get
(/Users/radomj/Library/Caches/Cypress/5.6.0/Cypress.app/Contents/Resources/app/packages/server/lib/errors.js:968:15)
    at Object._err
(/Users/radomj/Library/Caches/Cypress/5.6.0/Cypress.app/Contents/Resources/app/packages/server/lib/util/settings.js:65:22)
    at Object._logWriteErr
(/Users/radomj/Library/Caches/Cypress/5.6.0/Cypress.app/Contents/Resources/app/packages/server/lib/util/settings.js:77:17)
    at
/Users/radomj/Library/Caches/Cypress/5.6.0/Cypress.app/Contents/Resources/app/packages/server/lib/util/settings.js:84:19
    at tryCatcher
(/Users/radomj/Library/Caches/Cypress/5.6.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler
(/Users/radomj/Library/Caches/Cypress/5.6.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise
(/Users/radomj/Library/Caches/Cypress/5.6.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0
(/Users/radomj/Library/Caches/Cypress/5.6.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises
(/Users/radomj/Library/Caches/Cypress/5.6.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/promise.js:725:18)
    at _drainQueueStep
(/Users/radomj/Library/Caches/Cypress/5.6.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue
(/Users/radomj/Library/Caches/Cypress/5.6.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues
(/Users/radomj/Library/Caches/Cypress/5.6.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate]
(/Users/radomj/Library/Caches/Cypress/5.6.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:456:21)

```

**Comment by mbolotov** [comment] 2020-11-10 13:48
I still can't figure out what's going on there.
Do you start getting this after upgrade the plugin or not?

**Comment by jradom** [comment] 2020-11-11 05:30
Hi Mikhail,

Here is how you can replicate the issue:
Download locally this project
https://github.com/marcdacz/compare-pdf-cypress-js
Add it to IntelliJ Ultimate
Create a configuration like this
[image: image.png]
After the above project opening IntelliJ suggest to install Node and I did
(it does the latest one
node --version
v12.13.1)
Run it from IntelliJ and you'll see this
[image: image.png]
BTW, I run "npx cypress open" the code runs OK.
Oh, some simple Cypress projects work fine.  Strange
It'll be great if you'll find a way to fix it.  I have a demo  to deliver
early morning Friday PST

Cheers

Jeff

**Comment by jradom** [comment] 2020-11-11 06:22
other interesting observations.  Some very simple Cypress projects are
running fine using your plugin and my Cypress version is
[image: image.png]

**Comment by mbolotov** [comment] 2020-11-11 09:55
I cannot see the images you provided.
It looks like this:
![image](https://user-images.githubusercontent.com/19785715/98797025-192d9000-241d-11eb-84dd-f8c1b1ccd18d.png)

Could you resend them?

**Comment by jradom** [comment] 2020-11-11 15:29
Here you are again...  Please, let me if that worked this time
[image: image.png]

[image: image.png]
[image: image.png]
[image: image.png]



Thanks

Jeff

**Comment by mbolotov** [comment] 2020-11-11 15:51
unfortunately, it did not
Do you check the outlook as it shown at the 'Preview' tab? Does it show your images there?
Here is a recursive example :)
![image](https://user-images.githubusercontent.com/19785715/98833292-e7352180-244e-11eb-8580-ed738ba81780.png)

**Comment by jradom** [comment] 2020-11-11 17:07
and now?

**Comment by jradom** [comment] 2020-11-11 17:25
did zip file work?  Please, let me know

**Comment by mbolotov** [comment] 2020-11-11 19:39
no, I see nothing

**Comment by jradom** [comment] 2020-11-11 21:29
this is really weird.  Can you just give me an email where I can send
screenshots?  BTW, have you tried to download a Cypress project from my
email, set it up and run it?

**Comment by mbolotov** [comment] 2020-11-12 09:05
my email:
![image](https://user-images.githubusercontent.com/19785715/98918944-4cd0ee80-24df-11eb-9cc6-cd8ae84dff10.png)

Yes, I tried the project and run it successfully

**Comment by mbolotov** [comment] 2020-11-12 09:32
Okay, I've looked at screenshots.
You can try to define the Cypress project directory as the warning suggests
![image](https://user-images.githubusercontent.com/19785715/98922111-21e89980-24e3-11eb-90e7-88461177bb2e.png)

**Comment by jradom** [comment] 2020-11-12 09:55
Great.  It did work now but the error message was kinda unrelated and
confusing.  I suggests if possible to change it because any new user can
have the same issue

Cheers (Spasio)

Jeff
