### ISSUE TITLE
Intellij cypress plugin not running

### ISSUE THREAD

**Issue by pcouas** [mbolotov/intellij-cypress#7] opened 2020-05-18 08:00 UTC
"C:\Program Files (x86)\nodejs\node.exe" "C:\Program Files (x86)\nodejs\node_modules\npm\bin\npx-cli.js" cypress run --reporter D:/zpoubelle/pogues5/node_modules/cypress-intellij-reporter --spec D:/zpoubelle/pogues5/cypress/integration/examples/window.spec.js

Warning: We failed to trash the existing run results.

This error will not alter the exit code.

Error: Command failed: C:\Users\COUAS\AppData\Local\Cypress\Cache\4.5.0\Cypress\resources\app\packages\server\node_modules\trash\lib\win-trash.exe C:\zpoubelle\pogues5\cypress\screenshots\examples

    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)

Can't run because no spec files were found.

We searched for any files matching this glob pattern:

D:\zpoubelle\pogues5\cypress\integration\examples\window.spec.js

Process finished with exit code 1

Regards

**Comment by mbolotov** [comment] 2020-05-18 08:51
Hi @pcouas!
Thanks for reporting this.
Is that possible to provide a repo to reproduce the issue? I just have no clue what could be wrong reading the description.
And have you run your case successfully from the command line?

**Comment by pcouas** [comment] 2020-05-20 09:14
Hi
I have tested succesfully from command line
>npx cypress open --env EXTERNAL_API=localhost:3000 
Cypress open browser window

**Comment by mbolotov** [comment] 2020-05-20 09:27
can you run successfully it with just `npx cypress run`?

if `EXTERNAL_API` evn variable is required, you may set it the IDE's run configuration.
if it can be run using 'open' cypress command only you can set in the run configuration as well by using 'interactive' mode selector

**Comment by pcouas** [comment] 2020-05-20 10:08
Hi

 

Open command is running outside IntelliJ

Configuration contains environment variable, 

But i have flagged repository no spec file ?

 

Regards



 

 

 

 

> Message du 20/05/20 11:27
> De : "Mikhail Bolotov" 
> A : "mbolotov/intellij-cypress" 
> Copie à : "pcouas" 
, "Mention" 
> Objet : Re: [mbolotov/intellij-cypress] Intellij cypress plugin not running (#7)
> 
>
>

> can you run successfully it with just npx cypress run?

> if EXTERNAL_API evn variable is required, you may set it the IDE's run configuration.
> if it can be run using 'open' cypress command only you can set in the run configuration as well by using 'interactive' mode selector

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.

[ { "@context": "http://schema.org", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "https://github.com/mbolotov/intellij-cypress/issues/7#issuecomment-631357178", "url": "https://github.com/mbolotov/intellij-cypress/issues/7#issuecomment-631357178", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "https://github.com" } } ]

**Comment by mbolotov** [comment] 2020-05-20 10:16
could you please attach a screenshot of your run configuration in InteliJ?
and what about running just `npx cypress run` from command line?

**Comment by pcouas** [comment] 2020-05-20 10:17
Hi

>  

> Open command is running outside IntelliJ

> Configuration contains environment variable,

> But i have flagged repository no spec file ?

> Error message is on spec file ? 

 

 

 

> Regards

 

 

 

 

> Message du 20/05/20 11:27
> De : "Mikhail Bolotov" 
> A : "mbolotov/intellij-cypress" 
> Copie à : "pcouas" 
, "Mention" 
> Objet : Re: [mbolotov/intellij-cypress] Intellij cypress plugin not running (#7)
> 
>
>

> can you run successfully it with just npx cypress run?

> if EXTERNAL_API evn variable is required, you may set it the IDE's run configuration.
> if it can be run using 'open' cypress command only you can set in the run configuration as well by using 'interactive' mode selector

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.

[ { "@context": "http://schema.org", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "https://github.com/mbolotov/intellij-cypress/issues/7#issuecomment-631357178", "url": "https://github.com/mbolotov/intellij-cypress/issues/7#issuecomment-631357178", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "https://github.com" } } ]

**Comment by pcouas** [comment] 2020-05-20 10:29
from command line, it's Ok

 

 

 

> Message du 20/05/20 12:17
> De : "Mikhail Bolotov" 
> A : "mbolotov/intellij-cypress" 
> Copie à : "pcouas" 
, "Mention" 
> Objet : Re: [mbolotov/intellij-cypress] Intellij cypress plugin not running (#7)
> 
>
>

> could you please attach a screenshot of your run configuration in InteliJ?
> and what about running just npx cypress run from command line?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.

[ { "@context": "http://schema.org", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "https://github.com/mbolotov/intellij-cypress/issues/7#issuecomment-631383793", "url": "https://github.com/mbolotov/intellij-cypress/issues/7#issuecomment-631383793", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "https://github.com" } } ]

**Comment by mbolotov** [comment] 2020-05-20 10:42
okay, 
in sum, I need a reproducible repo to debug the problem.

**Comment by pcouas** [comment] 2020-05-20 11:52
Yes
test project is on https://github.com/EmmanuelDemey/Pogues/tree/cypress
cypress 4.4.1 on windows10 Pro
intelliJ ultimate 2020


D:\zpoubelle\pogues>npm version
{
  pogues: '0.0.2',
  npm: '6.14.5',
  ares: '1.16.0',
  brotli: '1.0.7',
  cldr: '36.0',
  http_parser: '2.9.3',
  icu: '65.1',
  llhttp: '2.0.4',
  modules: '72',
  napi: '5',
  nghttp2: '1.40.0',
  node: '12.16.3',
  openssl: '1.1.1g',
  tz: '2019c',
  unicode: '12.1',
  uv: '1.34.2',
  v8: '7.8.279.23-node.35',
  zlib: '1.2.11'
}

**Comment by mbolotov** [comment] 2020-05-20 13:29
I tried the repo (on the 'cypress' branch)
It works okay on my side with one issue:
Cypress expects a process environment variable to be set with the CYPRESS_ prefix.
But currently the plugin does not add this prefix automatically. 
So at the moment the correct way to set the EXTERNAL_API variable either this way:
![image](https://user-images.githubusercontent.com/19785715/82449979-b7671b80-9ab4-11ea-8849-ec7fc347c10c.png)
or directly via the cypress arguments:
![image](https://user-images.githubusercontent.com/19785715/82450048-d9609e00-9ab4-11ea-852f-fa428da212f4.png)


But anyway, I **could not** reproduce the error you mentioned:
`Can't run because no spec files were found`

When no EXTERNAL_API set, I got the following:
```
CypressError: `cy.visit()` must be called with a `url` or an `options` object containing a `url` as its 1st argument

https://on.cypress.io/visit

Because this error occurred during a `before each` hook we are skipping the remaining tests in the current suite: `Demo Cypress`
```
So you could try to set the env variable correctly but I'm not sure if this could help in fact.

**Comment by mbolotov** [comment] 2020-05-28 20:11
Hey @pcouas,
Are you still experiencing the issue?
If yes, could you please attach a zip of your project?

**Comment by mbolotov** [comment] 2020-06-04 08:47
closing as not reproducible 
@pcouas feel free to reopen if you can provide a project for reproducing the problem.

**Closed by mbolotov** 2020-06-04 08:47 UTC

**Comment by pcouas** [comment] 2020-06-08 06:58
Hi

 

it's not my project, it"s an webminar project

https://github.com/EmmanuelDemey/Pogues/tree/cypress

 

Regards

 

 

 

 

 

> Message du 28/05/20 22:11
> De : "Mikhail Bolotov" 
> A : "mbolotov/intellij-cypress" 
> Copie à : "pcouas" 
, "Mention" 
> Objet : Re: [mbolotov/intellij-cypress] Intellij cypress plugin not running (#7)
> 
>
>

> Hey @pcouas,
> Are you still experiencing the issue?
> If yes, could you please attach a zip of your project?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.

[ { "@context": "http://schema.org", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "https://github.com/mbolotov/intellij-cypress/issues/7#issuecomment-635575305", "url": "https://github.com/mbolotov/intellij-cypress/issues/7#issuecomment-635575305", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "https://github.com" } } ]

**Comment by mbolotov** [comment] 2020-06-08 21:04
Hi @pcouas!
yes, I have already tried the repository you mentioned. 
It works nice form me.
What I did:
1. checkout
2. npm install
3. npm start
4. in IDEA, create a run configuration via line marker provider:
![image](https://user-images.githubusercontent.com/19785715/84080095-501df680-a9e4-11ea-9855-823e280ddf39.png)
5. add the environment variable in the config:
![image](https://user-images.githubusercontent.com/19785715/84080187-7774c380-a9e4-11ea-825a-98f3f696bd85.png)
6. Run!

And finally get it passed:
![image](https://user-images.githubusercontent.com/19785715/84080262-94a99200-a9e4-11ea-9cbb-82d128609a44.png)

So I unable to reproduce you problem via the repository. 
Could you check you do the similar steps?

**Comment by pcouas** [comment] 2020-06-09 06:29
Hi

 

Problem is resolved now, but on Windows i need to use cypress 4.4.1 not cypress 4.5.0 and not cypress 4.6.0

 

Regards

 

 

 

 

> Message du 08/06/20 23:04
> De : "Mikhail Bolotov" 
> A : "mbolotov/intellij-cypress" 
> Copie à : "pcouas" 
, "Mention" 
> Objet : Re: [mbolotov/intellij-cypress] Intellij cypress plugin not running (#7)
> 
>
>

> Hi @pcouas!
> yes, I have already tried the repository you mentioned.
> It works nice form me.
> What I did:


checkout
npm install
npm start
in IDEA, create a run configuration via line marker provider:
> 
add the environment variable in the config:
> 
Run!

> And finally get it passed:
> 

> So I unable to reproduce you problem via the repository.
> Could you check you do the similar steps?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.

[ { "@context": "http://schema.org", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "https://github.com/mbolotov/intellij-cypress/issues/7#issuecomment-640885804", "url": "https://github.com/mbolotov/intellij-cypress/issues/7#issuecomment-640885804", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "https://github.com" } } ]
